package de.twyco.stegisagt;

public enum GameStatus {

    CLOSED,
    WAITING_FOR_PLAYERS,
    PLAYING,
    PLAYING_SCHATZSUCHE,
    PLAYING_AMPELRENNEN,
    PLAYING_TRUEORFALSE,
    PLAYING_HIDE_N_SEEK,
    PLAYING_MLG,
    PLAYING_SNOWFALL,
    PLAYING_MOLERACE,
    PLAYING_BLOCKPARTY,
    PLAYING_SPLEEF,
    PLAYING_REIHENFOLGE,
    //PLAYING_REISE_NACH_JERUSALEM,
    //PLAYING_BOWDUELL,

}
